// TODO: Удали ненужные поля типа:

// IntId: 100,
// Id: 'Iveco',
// IsPopular: true,

// и т.п.Id

const makesList = [
  {
    IntId: 100,
    Id: 'Iveco',
    Name: 'Iveco',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'iveco',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/IVECO_99_84x42_hrh.png',
      ThumbnailUri: '//i.avto.pro/storage/files/IVECO_99_84x42_hrh.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 101,
    Id: 'MAN',
    Name: 'MAN',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'man',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/MAN_100_84x42_wfn.png',
      ThumbnailUri: '//i.avto.pro/storage/files/MAN_100_84x42_wfn.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 102,
    Id: 'Mercedes',
    Name: 'Mercedes',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'mercedes-benz',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/MERCEDES_BENZ_101_84x42_29q.png',
      ThumbnailUri:
        '//i.avto.pro/storage/files/MERCEDES_BENZ_101_84x42_29q.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 105,
    Id: 'Renault Trucks',
    Name: 'Renault Trucks',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'renault',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/RENAULT_104_84x42_gbs.png',
      ThumbnailUri: '//i.avto.pro/storage/files/RENAULT_104_84x42_gbs.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 106,
    Id: 'Scania',
    Name: 'Scania',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'scania',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SCANIA_105_84x42_498.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SCANIA_105_84x42_498.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 107,
    Id: 'Volvo Trucks',
    Name: 'Volvo Trucks',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'volvo',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/VOLVO_106_84x42_x7m.png',
      ThumbnailUri: '//i.avto.pro/storage/files/VOLVO_106_84x42_x7m.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 11,
    Id: 'Daihatsu',
    Name: 'Daihatsu',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 3, Name: 'Japan', Link: 'catalog' },
    ],
    PopularInRegions: null,
    Link: 'daihatsu',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/DAIHATSU_10_84x42_i4r.png',
      ThumbnailUri: '//i.avto.pro/storage/files/DAIHATSU_10_84x42_i4r.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 110,
    Id: 'Jeep',
    Name: 'Jeep',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'jeep',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/JEEP_109_84x42_qdr.png',
      ThumbnailUri: '//i.avto.pro/storage/files/JEEP_109_84x42_qdr.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 111,
    Id: 'Ford',
    Name: 'Ford',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'ford',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/FORD_112_84x42_avl.png',
      ThumbnailUri: '//i.avto.pro/storage/files/FORD_112_84x42_avl.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 112,
    Id: 'Chrysler',
    Name: 'Chrysler',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'chrysler',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/CHRYSLER_113_84x42_0is.png',
      ThumbnailUri: '//i.avto.pro/storage/files/CHRYSLER_113_84x42_0is.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 113,
    Id: 'Dodge',
    Name: 'Dodge',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'dodge',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/DODGE_114_84x42_gxb.png',
      ThumbnailUri: '//i.avto.pro/storage/files/DODGE_114_84x42_gxb.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 114,
    Id: 'Lincoln',
    Name: 'Lincoln',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'lincoln',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/LINCOLN_115_84x42_hir.png',
      ThumbnailUri: '//i.avto.pro/storage/files/LINCOLN_115_84x42_hir.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 115,
    Id: 'Buick',
    Name: 'Buick',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'buick',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/BUICK_116_84x42_ext.png',
      ThumbnailUri: '//i.avto.pro/storage/files/BUICK_116_84x42_ext.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 121,
    Id: 'Geo',
    Name: 'Geo',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'geo',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/GEO_122_84x42_pv6.png',
      ThumbnailUri: '//i.avto.pro/storage/files/GEO_122_84x42_pv6.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 122,
    Id: 'Oldsmobile',
    Name: 'Oldsmobile',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'oldsmobile',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/OLDSMOBILE_123_84x42_q41.png',
      ThumbnailUri: '//i.avto.pro/storage/files/OLDSMOBILE_123_84x42_q41.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 125,
    Id: 'Plymouth',
    Name: 'Plymouth',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'plymouth',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/PLYMOUTH_126_84x42_0qe.png',
      ThumbnailUri: '//i.avto.pro/storage/files/PLYMOUTH_126_84x42_0qe.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 126,
    Id: 'Nissan',
    Name: 'Nissan',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
      { Id: 3, Name: 'Japan', Link: 'catalog' },
    ],
    PopularInRegions: null,
    Link: 'nissan',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/NISSAN_127_84x42_kor.png',
      ThumbnailUri: '//i.avto.pro/storage/files/NISSAN_127_84x42_kor.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 127,
    Id: 'Cadillac',
    Name: 'Cadillac',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'cadillac',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/CADILLAC_128_84x42_lzh.png',
      ThumbnailUri: '//i.avto.pro/storage/files/CADILLAC_128_84x42_lzh.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 128,
    Id: 'Pontiac',
    Name: 'Pontiac',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'pontiac',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/PONTIAC_131_84x42_kn1.png',
      ThumbnailUri: '//i.avto.pro/storage/files/PONTIAC_131_84x42_kn1.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 132,
    Id: 'Saturn',
    Name: 'Saturn',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'saturn',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SATURN_135_84x42_9ip.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SATURN_135_84x42_9ip.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 133,
    Id: 'Lada',
    Name: 'Lada',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'lada',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/Lada_VAZ_136_84x42_91u.png',
      ThumbnailUri: '//i.avto.pro/storage/files/Lada_VAZ_136_84x42_91u.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 134,
    Id: 'Lexus',
    Name: 'Lexus',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'lexus',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/LEXUS_137_84x42_74p.png',
      ThumbnailUri: '//i.avto.pro/storage/files/LEXUS_137_84x42_74p.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 135,
    Id: 'Hummer',
    Name: 'Hummer',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'hummer',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/HUMMER_138_84x42_3fo.png',
      ThumbnailUri: '//i.avto.pro/storage/files/HUMMER_138_84x42_3fo.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 136,
    Id: 'Mercury',
    Name: 'Mercury',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'mercury',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/MERCURY_139_84x42_e0q.png',
      ThumbnailUri: '//i.avto.pro/storage/files/MERCURY_139_84x42_e0q.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 137,
    Id: 'Eagle',
    Name: 'Eagle',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'eagle',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/EAGLE_140_84x42_g39.png',
      ThumbnailUri: '//i.avto.pro/storage/files/EAGLE_140_84x42_g39.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 138,
    Id: 'Chevrolet',
    Name: 'Chevrolet',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'chevrolet',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/CHEVROLET-EUR_141_84x42_gl4.png',
      ThumbnailUri:
        '//i.avto.pro/storage/files/CHEVROLET-EUR_141_84x42_gl4.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 140,
    Id: 'Proton',
    Name: 'Proton',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'proton',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/PROTON_143_84x42_rbb.png',
      ThumbnailUri: '//i.avto.pro/storage/files/PROTON_143_84x42_rbb.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 141,
    Id: 'Great Wall',
    Name: 'Great Wall',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'great-wall',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/GREATWALL_144_84x42_lso.png',
      ThumbnailUri: '//i.avto.pro/storage/files/GREATWALL_144_84x42_lso.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 145,
    Id: 'KIA',
    Name: 'KIA',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'kia',
    IsPopular: false,
    Logo: null,
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 146,
    Id: 'BYD',
    Name: 'BYD',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'byd',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/BYD_149_84x42_tcs.png',
      ThumbnailUri: '//i.avto.pro/storage/files/BYD_149_84x42_tcs.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 147,
    Id: 'FAW',
    Name: 'FAW',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'faw',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/FAW_150_84x42_4yw.png',
      ThumbnailUri: '//i.avto.pro/storage/files/FAW_150_84x42_4yw.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 148,
    Id: 'Xin kai',
    Name: 'Xin kai',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'xin-kai',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/XINKAI_151_84x42_ix3.png',
      ThumbnailUri: '//i.avto.pro/storage/files/XINKAI_151_84x42_ix3.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 149,
    Id: 'Hafei',
    Name: 'Hafei',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'hafei',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/HAFEI_152_84x42_445.png',
      ThumbnailUri: '//i.avto.pro/storage/files/HAFEI_152_84x42_445.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 150,
    Id: 'MINI',
    Name: 'MINI',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'mini',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/MINI_153_84x42_q07.png',
      ThumbnailUri: '//i.avto.pro/storage/files/MINI_153_84x42_q07.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 152,
    Id: 'Honda',
    Name: 'Honda',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
      { Id: 3, Name: 'Japan', Link: 'catalog' },
    ],
    PopularInRegions: null,
    Link: 'honda',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/HONDA_172_84x42_bql.png',
      ThumbnailUri: '//i.avto.pro/storage/files/HONDA_172_84x42_bql.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 153,
    Id: 'Isuzu',
    Name: 'Isuzu',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
      { Id: 3, Name: 'Japan', Link: 'catalog' },
    ],
    PopularInRegions: null,
    Link: 'isuzu',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/ISUZU_173_84x42_zph.png',
      ThumbnailUri: '//i.avto.pro/storage/files/ISUZU_173_84x42_zph.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 154,
    Id: 'Mazda',
    Name: 'Mazda',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
      { Id: 3, Name: 'Japan', Link: 'catalog' },
    ],
    PopularInRegions: null,
    Link: 'mazda',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/MAZDA_174_84x42_38s.png',
      ThumbnailUri: '//i.avto.pro/storage/files/MAZDA_174_84x42_38s.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 155,
    Id: 'Mitsubishi',
    Name: 'Mitsubishi',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
      { Id: 3, Name: 'Japan', Link: 'catalog' },
    ],
    PopularInRegions: null,
    Link: 'mitsubishi',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/MITSUBISHI_175_84x42_4q0.png',
      ThumbnailUri: '//i.avto.pro/storage/files/MITSUBISHI_175_84x42_4q0.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 158,
    Id: 'Subaru',
    Name: 'Subaru',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
      { Id: 3, Name: 'Japan', Link: 'catalog' },
    ],
    PopularInRegions: null,
    Link: 'subaru',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SUBARU_178_84x42_2g1.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SUBARU_178_84x42_2g1.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 159,
    Id: 'Suzuki',
    Name: 'Suzuki',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
      { Id: 3, Name: 'Japan', Link: 'catalog' },
    ],
    PopularInRegions: null,
    Link: 'suzuki',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SUZUKI_179_84x42_7r6.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SUZUKI_179_84x42_7r6.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 160,
    Id: 'Toyota',
    Name: 'Toyota',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
      { Id: 3, Name: 'Japan', Link: 'catalog' },
    ],
    PopularInRegions: null,
    Link: 'toyota',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/TOYOTA_180_84x42_hfq.png',
      ThumbnailUri: '//i.avto.pro/storage/files/TOYOTA_180_84x42_hfq.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 161,
    Id: 'Hyundai',
    Name: 'Hyundai',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'hyundai',
    IsPopular: true,
    Logo: null,
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 162,
    Id: 'Dacia',
    Name: 'Dacia',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'dacia',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/DACIA_182_84x42_2dk.png',
      ThumbnailUri: '//i.avto.pro/storage/files/DACIA_182_84x42_2dk.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 163,
    Id: 'Dongfeng',
    Name: 'Dongfeng',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'dongfeng',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/DONGFENG_183_84x42_660.png',
      ThumbnailUri: '//i.avto.pro/storage/files/DONGFENG_183_84x42_660.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 164,
    Id: 'BAW',
    Name: 'BAW',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'baw',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/BAW_184_84x42_ukm.png',
      ThumbnailUri: '//i.avto.pro/storage/files/BAW_184_84x42_ukm.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 165,
    Id: 'Foton',
    Name: 'Foton',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'foton',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/FOTON_185_84x42_bnd.png',
      ThumbnailUri: '//i.avto.pro/storage/files/FOTON_185_84x42_bnd.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 166,
    Id: 'Chery',
    Name: 'Chery',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'chery',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/CHERY_186_84x42_6ys.png',
      ThumbnailUri: '//i.avto.pro/storage/files/CHERY_186_84x42_6ys.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 167,
    Id: 'SMA Maple',
    Name: 'SMA Maple',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'sma-maple',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SMA-MAPLE_187_84x42_ndc.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SMA-MAPLE_187_84x42_ndc.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 168,
    Id: 'Derways',
    Name: 'Derways',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'derways',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/DERWAYS_188_84x42_bph.png',
      ThumbnailUri: '//i.avto.pro/storage/files/DERWAYS_188_84x42_bph.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 169,
    Id: 'Geely',
    Name: 'Geely',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'geely',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/GEELY_189_84x42_2h0.png',
      ThumbnailUri: '//i.avto.pro/storage/files/GEELY_189_84x42_2h0.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 171,
    Id: 'Porsche',
    Name: 'Porsche',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'porsche',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/PORSCHE_191_84x42_hps.png',
      ThumbnailUri: '//i.avto.pro/storage/files/PORSCHE_191_84x42_hps.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 175,
    Id: 'Lifan',
    Name: 'Lifan',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'lifan',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/LIFAN_195_84x42_0z2.png',
      ThumbnailUri: '//i.avto.pro/storage/files/LIFAN_195_84x42_0z2.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 176,
    Id: 'Brilliance',
    Name: 'Brilliance',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'brilliance',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/BRILLIANCE_196_84x42_ra6.png',
      ThumbnailUri: '//i.avto.pro/storage/files/BRILLIANCE_196_84x42_ra6.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 177,
    Id: 'Chana',
    Name: 'Chana',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'chana',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/CHANA_197_84x42_itl.png',
      ThumbnailUri: '//i.avto.pro/storage/files/CHANA_197_84x42_itl.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 178,
    Id: 'Changfeng',
    Name: 'Changfeng',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'changfeng',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/CHANG-FENG_198_84x42_lvm.png',
      ThumbnailUri: '//i.avto.pro/storage/files/CHANG-FENG_198_84x42_lvm.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 179,
    Id: 'Golden Dragon',
    Name: 'Golden Dragon',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'golden-dragon',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/GOLDEN-DRAGON_199_84x42_f7k.png',
      ThumbnailUri:
        '//i.avto.pro/storage/files/GOLDEN-DRAGON_199_84x42_f7k.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 18,
    Id: 'Jaguar',
    Name: 'Jaguar',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'jaguar',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/JAGUAR_17_84x42_gt0.png',
      ThumbnailUri: '//i.avto.pro/storage/files/JAGUAR_17_84x42_gt0.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 180,
    Id: 'Gonow',
    Name: 'Gonow',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'gonow',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/GONOW_200_84x42_od5.png',
      ThumbnailUri: '//i.avto.pro/storage/files/GONOW_200_84x42_od5.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 181,
    Id: 'Groz',
    Name: 'Groz',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'groz',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/GROZ_202_84x42_an0.png',
      ThumbnailUri: '//i.avto.pro/storage/files/GROZ_202_84x42_an0.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 182,
    Id: 'Haima',
    Name: 'Haima',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'haima',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/Haima_203_84x42_urg.png',
      ThumbnailUri: '//i.avto.pro/storage/files/Haima_203_84x42_urg.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 183,
    Id: 'Huanghai',
    Name: 'Huanghai',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'huanghai',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/HUANGHAI_204_84x42_sqr.png',
      ThumbnailUri: '//i.avto.pro/storage/files/HUANGHAI_204_84x42_sqr.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 184,
    Id: 'JAC',
    Name: 'JAC',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'jac',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/JAC_205_84x42_c2d.png',
      ThumbnailUri: '//i.avto.pro/storage/files/JAC_205_84x42_c2d.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 185,
    Id: 'Jinbei',
    Name: 'Jinbei',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'jinbei',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/JINBEI_206_84x42_5vm.png',
      ThumbnailUri: '//i.avto.pro/storage/files/JINBEI_206_84x42_5vm.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 186,
    Id: 'Landwind',
    Name: 'Landwind',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'landwind',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/LANDWIND_207_84x42_shk.png',
      ThumbnailUri: '//i.avto.pro/storage/files/LANDWIND_207_84x42_shk.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 188,
    Id: 'Samand',
    Name: 'Samand',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'samand',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SAMAND_209_84x42_x1w.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SAMAND_209_84x42_x1w.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 189,
    Id: 'Yuejin',
    Name: 'Yuejin',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'yuejin',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/YUEJIN_210_84x42_rgr.png',
      ThumbnailUri: '//i.avto.pro/storage/files/YUEJIN_210_84x42_rgr.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 190,
    Id: 'Zhongxing',
    Name: 'Zhongxing',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'zhongxing',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/ZX-Zhongxing_211_84x42_dv9.png',
      ThumbnailUri: '//i.avto.pro/storage/files/ZX-Zhongxing_211_84x42_dv9.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 191,
    Id: 'JMC',
    Name: 'JMC',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'jmc',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/JMC_212_84x42_6bl.png',
      ThumbnailUri: '//i.avto.pro/storage/files/JMC_212_84x42_6bl.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 192,
    Id: 'Higer',
    Name: 'Higer',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'higer',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/HIGER_213_84x42_vcq.png',
      ThumbnailUri: '//i.avto.pro/storage/files/HIGER_213_84x42_vcq.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 193,
    Id: 'Shaolin',
    Name: 'Shaolin',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'shaolin',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SHAOLIN_214_84x42_rhg.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SHAOLIN_214_84x42_rhg.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 194,
    Id: 'Yutong',
    Name: 'Yutong',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'yutong',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/YUTONG_215_84x42_m1h.png',
      ThumbnailUri: '//i.avto.pro/storage/files/YUTONG_215_84x42_m1h.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 195,
    Id: 'Mudan',
    Name: 'Mudan',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'mudan',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/MUDAN_216_84x42_v1g.png',
      ThumbnailUri: '//i.avto.pro/storage/files/MUDAN_216_84x42_v1g.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 196,
    Id: 'Zonda',
    Name: 'Zonda',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'zonda',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/ZONDA_217_84x42_v6k.png',
      ThumbnailUri: '//i.avto.pro/storage/files/ZONDA_217_84x42_v6k.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 197,
    Id: 'Infiniti',
    Name: 'Infiniti',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'infiniti',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/INFINITI_218_84x42_lky.png',
      ThumbnailUri: '//i.avto.pro/storage/files/INFINITI_218_84x42_lky.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 198,
    Id: 'Dadi',
    Name: 'Dadi',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'dadi',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/DADI_219_84x42_zdy.png',
      ThumbnailUri: '//i.avto.pro/storage/files/DADI_219_84x42_zdy.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 199,
    Id: 'Tianma',
    Name: 'Tianma',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'tianma',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/TIANMA_220_84x42_dqy.png',
      ThumbnailUri: '//i.avto.pro/storage/files/TIANMA_220_84x42_dqy.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 2,
    Id: 'Acura',
    Name: 'Acura',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'acura',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/ACURA_1_84x42_dgp.png',
      ThumbnailUri: '//i.avto.pro/storage/files/ACURA_1_84x42_dgp.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 20,
    Id: 'Lancia',
    Name: 'Lancia',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'lancia',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/LANCIA_19_84x42_x9o.png',
      ThumbnailUri: '//i.avto.pro/storage/files/LANCIA_19_84x42_x9o.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 200,
    Id: 'Soueast',
    Name: 'Soueast',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'soueast',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SOUEAST_221_84x42_pot.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SOUEAST_221_84x42_pot.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 201,
    Id: 'Shuanghuan',
    Name: 'Shuanghuan',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'shuanghuan',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SHUANGHUAN_222_84x42_vig.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SHUANGHUAN_222_84x42_vig.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 203,
    Id: 'Tianye',
    Name: 'Tianye',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'tianye',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/TIANYE_224_84x42_epc.png',
      ThumbnailUri: '//i.avto.pro/storage/files/TIANYE_224_84x42_epc.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 204,
    Id: 'Howo',
    Name: 'Howo',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'howo',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/HOWO_225_84x42_a2c.png',
      ThumbnailUri: '//i.avto.pro/storage/files/HOWO_225_84x42_a2c.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 205,
    Id: 'Hania',
    Name: 'Hania',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'hania',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/HANIA_226_84x42_txz.png',
      ThumbnailUri: '//i.avto.pro/storage/files/HANIA_226_84x42_txz.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 206,
    Id: 'Shaanxi',
    Name: 'Shaanxi',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'shaanxi',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SHAANXI_227_84x42_czn.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SHAANXI_227_84x42_czn.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 207,
    Id: 'Beifang Benchi',
    Name: 'Beifang Benchi',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'beifang-benchi',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/BEIFANG-BENCHI_228_84x42_sgs.png',
      ThumbnailUri:
        '//i.avto.pro/storage/files/BEIFANG-BENCHI_228_84x42_sgs.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 21,
    Id: 'Land Rover',
    Name: 'Land Rover',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'land-rover',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/LAND-ROVER_20_84x42_4v3.png',
      ThumbnailUri: '//i.avto.pro/storage/files/LAND-ROVER_20_84x42_4v3.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 213,
    Id: 'Smart',
    Name: 'Smart',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'smart',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SMART_230_84x42_wc1.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SMART_230_84x42_wc1.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 215,
    Id: 'Changan',
    Name: 'Changan',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'changan',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/Changan_231_84x42_x7m.png',
      ThumbnailUri: '//i.avto.pro/storage/files/Changan_231_84x42_x7m.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 217,
    Id: 'Vortex',
    Name: 'Vortex',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'vortex',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/Vortex_233_84x42_7vf.png',
      ThumbnailUri: '//i.avto.pro/storage/files/Vortex_233_84x42_7vf.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 224,
    Id: 'Maserati',
    Name: 'Maserati',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'maserati',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/Maserati_241_84x42_lzc.png',
      ThumbnailUri: '//i.avto.pro/storage/files/Maserati_241_84x42_lzc.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 227,
    Id: 'LDV',
    Name: 'LDV',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'ldv',
    IsPopular: false,
    Logo: null,
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 229,
    Id: 'Tesla',
    Name: 'Tesla',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'tesla',
    IsPopular: false,
    Logo: null,
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 230,
    Id: 'Fiat',
    Name: 'Fiat',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'fiat',
    IsPopular: false,
    Logo: null,
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 232,
    Id: 'GMC',
    Name: 'GMC',
    Regions: [{ Id: 2, Name: 'USA', Link: 'catalog-amerika' }],
    PopularInRegions: null,
    Link: 'gmc',
    IsPopular: false,
    Logo: null,
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 233,
    Id: 'MORRIS GARAGE',
    Name: 'MORRIS GARAGE',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'mg',
    IsPopular: false,
    Logo: null,
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 27,
    Id: 'Opel',
    Name: 'Opel',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'opel',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/OPEL_26_84x42_hwd.png',
      ThumbnailUri: '//i.avto.pro/storage/files/OPEL_26_84x42_hwd.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 28,
    Id: 'Peugeot',
    Name: 'Peugeot',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'peugeot',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/PEUGEOT_27_84x42_i39.png',
      ThumbnailUri: '//i.avto.pro/storage/files/PEUGEOT_27_84x42_i39.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 3,
    Id: 'Alfa Romeo',
    Name: 'Alfa Romeo',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'alfa-romeo',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/ALFA-ROMEO_2_84x42_tzl.png',
      ThumbnailUri: '//i.avto.pro/storage/files/ALFA-ROMEO_2_84x42_tzl.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 30,
    Id: 'Renault',
    Name: 'Renault',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'renault',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/RENAULT_29_84x42_gbc.png',
      ThumbnailUri: '//i.avto.pro/storage/files/RENAULT_29_84x42_gbc.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 31,
    Id: 'Rover',
    Name: 'Rover',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'rover',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/ROVER_30_84x42_uis.png',
      ThumbnailUri: '//i.avto.pro/storage/files/ROVER_30_84x42_uis.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 32,
    Id: 'Saab',
    Name: 'Saab',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'saab',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SAAB_31_84x42_e73.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SAAB_31_84x42_e73.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 33,
    Id: 'Seat',
    Name: 'Seat',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'seat',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SEAT_32_84x42_etz.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SEAT_32_84x42_etz.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 34,
    Id: 'Skoda',
    Name: 'Skoda',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'skoda',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SKODA_33_84x42_9ke.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SKODA_33_84x42_9ke.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 35,
    Id: 'SsangYong',
    Name: 'SsangYong',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'ssangyong',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/SSANG-YONG_34_84x42_umd.png',
      ThumbnailUri: '//i.avto.pro/storage/files/SSANG-YONG_34_84x42_umd.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 38,
    Id: 'Talbot',
    Name: 'Talbot',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'talbot',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/TALBOT_37_84x42_mnv.png',
      ThumbnailUri: '//i.avto.pro/storage/files/TALBOT_37_84x42_mnv.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 4,
    Id: 'Asia Motors',
    Name: 'Asia Motors',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'asia-motors',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/ASIA-MOTORS_3_84x42_bt8.png',
      ThumbnailUri: '//i.avto.pro/storage/files/ASIA-MOTORS_3_84x42_bt8.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 40,
    Id: 'Vauxhall',
    Name: 'Vauxhall',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'vauxhall',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/Vauxhall_39_84x42_q6h.png',
      ThumbnailUri: '//i.avto.pro/storage/files/Vauxhall_39_84x42_q6h.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 41,
    Id: 'Volvo',
    Name: 'Volvo',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'volvo',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/VOLVO_40_84x42_qgd.png',
      ThumbnailUri: '//i.avto.pro/storage/files/VOLVO_40_84x42_qgd.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 42,
    Id: 'Volkswagen',
    Name: 'Volkswagen',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'volkswagen',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/VOLKSWAGEN_41_84x42_yxz.png',
      ThumbnailUri: '//i.avto.pro/storage/files/VOLKSWAGEN_41_84x42_yxz.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 43,
    Id: 'Wartburg',
    Name: 'Wartburg',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'wartburg',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/WARTBURG_42_84x42_h1z.png',
      ThumbnailUri: '//i.avto.pro/storage/files/WARTBURG_42_84x42_h1z.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 5,
    Id: 'Audi',
    Name: 'Audi',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'audi',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/AUDI_4_84x42_ywa.png',
      ThumbnailUri: '//i.avto.pro/storage/files/AUDI_4_84x42_ywa.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 6,
    Id: 'Austin',
    Name: 'Austin',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'austin',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/AUSTIN_5_84x42_ox1.png',
      ThumbnailUri: '//i.avto.pro/storage/files/AUSTIN_5_84x42_ox1.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 7,
    Id: 'BMW',
    Name: 'BMW',
    Regions: [
      { Id: 1, Name: 'Europe', Link: 'catalog' },
      { Id: 2, Name: 'USA', Link: 'catalog-amerika' },
    ],
    PopularInRegions: null,
    Link: 'bmw',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/BMW_6_84x42_gug.png',
      ThumbnailUri: '//i.avto.pro/storage/files/BMW_6_84x42_gug.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 8,
    Id: 'Citroen',
    Name: 'Citroen',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'citroen',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/CITROEN_7_84x42_71r.png',
      ThumbnailUri: '//i.avto.pro/storage/files/CITROEN_7_84x42_71r.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 9,
    Id: 'Daewoo',
    Name: 'Daewoo',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'daewoo',
    IsPopular: true,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/DAEWOO_8_84x42_n9p.png',
      ThumbnailUri: '//i.avto.pro/storage/files/DAEWOO_8_84x42_n9p.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
  {
    IntId: 99,
    Id: 'DAF',
    Name: 'DAF',
    Regions: [{ Id: 1, Name: 'Europe', Link: 'catalog' }],
    PopularInRegions: null,
    Link: 'daf',
    IsPopular: false,
    Logo: {
      Id: 0,
      ImageUri: '//i.avto.pro/storage/files/DAF_98_84x42_o5x.png',
      ThumbnailUri: '//i.avto.pro/storage/files/DAF_98_84x42_o5x.png',
    },
    OriginalCatalogUri: null,
    SupportsSearchByVin: false,
  },
];

export default makesList;
